package main

import "fmt"

// var Level105 = BuildLevel([]Vial{
// 	{DBLUE, DGREEN, LBLUE, LBLUE},
// 	{VIOLET, PINK, LGREEN, GRAY},
// 	{ORANGE, VIOLET, RED, BROWN},
// 	{ORANGE, PINK, RED, ORANGE},
// 	{DGREEN, RED, YELLOW, DBLUE},
// 	{YELLOW, DGREEN, BROWN, DGREEN},
// 	{BROWN, VIOLET, RED, BGREEN},
// 	{BGREEN, VIOLET, PINK, BGREEN},
// 	{LGREEN, GRAY, LBLUE, DBLUE},
// 	{BROWN, YELLOW, GRAY, LGREEN},
// 	{GRAY, YELLOW, BGREEN, DBLUE},
// 	{LGREEN, LBLUE, PINK, ORANGE},
// 	{AIR, AIR, AIR, AIR},
// 	{AIR, AIR, AIR, AIR},
// })

// var Level105 = BuildLevel([]Vial{
// 	{DBLUE, DBLUE, DGREEN, LBLUE, LBLUE},
// 	{VIOLET, VIOLET, PINK, LGREEN, GRAY},
// 	{ORANGE, ORANGE, VIOLET, RED, BROWN},
// 	{PINK, ORANGE, PINK, RED, ORANGE},
// 	{RED, DGREEN, RED, YELLOW, DBLUE},
// 	{BROWN, YELLOW, DGREEN, BROWN, DGREEN},
// 	{BGREEN, BROWN, VIOLET, RED, BGREEN},
// 	{DGREEN, BGREEN, VIOLET, PINK, BGREEN},
// 	{YELLOW, LGREEN, GRAY, LBLUE, DBLUE},
// 	{LGREEN, BROWN, YELLOW, GRAY, LGREEN},
// 	{LBLUE, GRAY, YELLOW, BGREEN, DBLUE},
// 	{GRAY, LGREEN, LBLUE, PINK, ORANGE},
// 	{AIR, AIR, AIR, AIR, AIR},
// 	{AIR, AIR, AIR, AIR, AIR},
// })

var Level105 = BuildLevel([]Vial{
	{DBLUE, ORANGE, DBLUE, DBLUE, DBLUE},
	{VIOLET, DBLUE, VIOLET, VIOLET, VIOLET},
	{ORANGE, ORANGE, VIOLET, ORANGE, ORANGE},
	{RED, PINK, PINK, PINK, PINK},
	{PINK, RED, RED, RED, RED},

	{AIR, AIR, AIR, AIR, AIR},
	{AIR, AIR, AIR, AIR, AIR},
})

// var Level106 = BuildLevel([]Vial{
// 	{VIOLET, RED, BGREEN, PINK},
// 	{PINK, LGREEN, DBLUE, DBLUE},
// 	{DBLUE, LBLUE, LBLUE, GRAY},
// 	{PINK, LGREEN, BGREEN, LGREEN},
// 	{GRAY, VIOLET, ORANGE, ORANGE},
// 	{PINK, RED, ORANGE, LGREEN},
// 	{RED, BGREEN, GRAY, GRAY},
// 	{ORANGE, VIOLET, RED, BGREEN},
// 	{VIOLET, DBLUE, LBLUE, LBLUE},
// 	{AIR, AIR, AIR, AIR},
// 	{AIR, AIR, AIR, AIR},
// })

// var Level107 = BuildLevel([]Vial{
// 	{BGREEN, GRAY, ORANGE, YELLOW},
// 	{RED, VIOLET, LGREEN, LBLUE},
// 	{LGREEN, PINK, BGREEN, VIOLET},
// 	{YELLOW, PINK, RED, BROWN},
// 	{LGREEN, DBLUE, BROWN, VIOLET},
// 	{LGREEN, GRAY, VIOLET, YELLOW},
// 	{ORANGE, GRAY, LBLUE, DGREEN},

// 	{RED, DGREEN, LBLUE, PINK},
// 	{DBLUE, DBLUE, LBLUE, BGREEN},
// 	{DGREEN, BROWN, PINK, ORANGE},
// 	{GRAY, BGREEN, YELLOW, ORANGE},
// 	{RED, BROWN, DGREEN, DBLUE},
// 	{AIR, AIR, AIR, AIR},
// 	{AIR, AIR, AIR, AIR},
// })

func main() {
	InitialiseLevelBuffers(100)
	shortest := false
	fmt.Println("Solving Level 105, find shortest:", shortest)
	sol := Level105.Solve(shortest, true)
	for i, s := range sol {
		fmt.Printf("Move %2d: %2d -> %2d\n", i+1, s[0]+1, s[1]+1)
	}

}
